### ISSUE TITLE
item upgrades when equipped not upgrading equipped item?

### ISSUE THREAD

**Issue by briaguya-ai** [briaguya-ai/rando-issue-tracker#10]
edit: upgrading hookshot to longshot or fairy ocarina to oot doesn't upgrade equipped item in other age

repro steps:
* be child
* get fairy ocarina
* go adult
* get oot
* go child
* still have fairy ocarina equipped

**OR**

* be adult
* get hookshot
* go child
* get longshot
* go adult
* hookshot still equipped

getting longshot when hookshot is equipped doesn't replace equip with longshot (not sure if this happens in dev), same happens with fairy/oot but i think that wouldn't be problem outside of rando because cutscene

**Comment by shadeRed** [comment]
can confirm, getting item upgrades in dev replaces the equip (if any)

**Comment by briaguya-ai** [comment]
not sure how to reproduce this, i tried manually editing a spoilerfile to have
```
"KF Mido Bottom Left Chest": "Progressive Hookshot",
"KF Mido Bottom Right Chest": "Progressive Hookshot",
"KF Mido Top Left Chest": "Progressive Ocarina",
"KF Mido Top Right Chest": "Progressive Ocarina",
```
and as soon as i get the second item the equipped c button item updates

i know the original issue report on discord didn't mention the icon for the longshot, but instead that the chain was short, maybe need to try in a more open area?

**Comment by Drihscol** [comment]
Issue seems to be when adult has hookshot equipped, and child picks up longshot.
Longshot does not update adult's equips if you are child.

https://streamable.com/ts98a3
