### ISSUE TITLE
goron city spinning pot won't give big smile when reward is bombs

### ISSUE THREAD

**Issue by briaguya-ai** [briaguya-ai/rando-issue-tracker#107]
my guess is the logic for the pot checks the reward when determining what face to show

**Comment by aMannus** [comment]
Could you elaborate? I don't really understand.

**Comment by aMannus** [comment]
I know the vanilla behaviour, but what's currently happening in SoH? Is it just not giving a reward when you hit the smiley face, or does it never stop on the smiley face to begin with?

**Comment by briaguya-ai** [comment]
never stops on the smiley face

**Comment by aMannus** [comment]
That's.. freaking weird. Alright thanks.
