### ISSUE TITLE
holding "R" when going to the lost woods bridge kills the fairy ocarina check

### ISSUE THREAD

**Issue by briaguya-ai** [briaguya-ai/rando-issue-tracker#117]
probably similar to https://github.com/briaguya-ai/Shipwright/pull/287

**Comment by briaguya-ai** [comment]
calling this good with the current fix, @leggettc18 if you want to make a new issue for link being able to shield himself from ice traps and mark it as not v1 that works, otherwise i'm good to call it done

**Comment by leggettc18** [comment]
I have plans for a system to prevent flags from getting set too early that would fix that, so I'll make an issue about that.
