### ISSUE TITLE
prelude check doesn't trigger immediately after traveling forward in time

### ISSUE THREAD

**Issue by briaguya-ai** [briaguya-ai/rando-issue-tracker#12]
couldn't figure out how to make it so you get the prelude item immediately after traveling forward in time with the forest medallion, for now you have to walk through the door and back to get that to trigger...

**Comment by leggettc18** [comment]
When you say "through the door and back", are you referring to the door of time or all the way out of the temple?

**Comment by leggettc18** [comment]
I might have an idea of why this is happening. I think the check is only triggering during the loading of the full poly master sword room. If I noclip around the loading zone so I'm standing in the low poly version of the master sword room, and walk back through the hallway, I get the check as soon as I hit the loading zone where the full poly room loads in.

**Comment by briaguya-ai** [comment]
> When you say "through the door and back", are you referring to the door of time or all the way out of the temple?

door of time, the check is in the master sword pedestal init function, so when that unloads/loads it triggers

i tried moving it off/adding another call when traveling through time bun ran into issues with that (don't remember what issues exactly)

**Comment by leggettc18** [comment]
I did some debugging with a breakpoint and stepping around, and it looks like the check is actually triggering, but its triggering during the time travelling animation, and eventually it gets to this line in z_actor.c and something here returns false.

```
if ((((player->heldActor != NULL) || (actor == player->targetActor)) && (getItemId > GI_NONE) &&
             (getItemId < GI_MAX)) ||
            (!(player->stateFlags1 & 0x20000800)))
```

**Comment by briaguya-ai** [comment]
did you see what the values were for all of those? (`heldActor`/`targetActor` etc.)

also, if we try to give link the item while it's still a cutscene we run into issues, we need to make sure that happens after link gets out of the blocking cutscene state

**Comment by leggettc18** [comment]
I didn't have time to check all of those this morning before going to work, but I can check later. But I wouldn't be surprised if this is getting evaluated to false precisely because we're in a cutscene. Last night I experimented with checking during the update function of toki_swd, and that did correctly give the item but then immediately triggered the time travel again. Does Sheik's BlockPedestal action get called at all or is her actor just completely killed in rando?

**Comment by leggettc18** [comment]
<!DOCTYPE html>
<HTML>
<head>
<title>Document</title></head>
<body>



  | Name | Value | Type
-- | -- | -- | --
  | GI_MAX | GI_MAX (0x00000096) | GetItemID
  | GI_NONE | GI_NONE (0x00000000) | GetItemID
▶ | actor | 0x000001ec198d1eb0 {id=0x0048 category=0x04 '\x4' room=0x00 '\0' ...} | Actor *
  | getItemId | 0x0000008c | int
▶ | player | 0x000001ec198cc840 {actor={id=0x0000 category=0x02 '\x2' room=0xff 'ÿ' ...} currentTunic=0x00 '\0' currentSwordItem=...} | Player *
▶ | player->heldActor | 0x0000000000000000 <NULL> | Actor *
  | player->stateFlags1 | 0x20000000 | unsigned int
▶ | player->targetActor | 0x0000000000000000 <NULL> | Actor *



</body>
</HTML>

Here's the values of those flags. There's a metric ton of nested values but none of them are relevant to the above if statement. It seems to be related to either the player->heldActor and player->targetActor being null, and/or the player->stateFlags1 not being the same as that hex value, thus returning a nonzero value, and negating to false. Not sure exactly what it means yet.

**Comment by leggettc18** [comment]
Yeah I can get the check to trigger anywhere in that room, but for some reason whenever it actually succeeds in giving you the item, it triggers the time travel back to the past... and I have no idea why that happens.

**Comment by leggettc18** [comment]
Ok. this isn't necessarily as good as it could be, but I managed to make it so that it will trigger on your way out of the Master Sword room (during the master sword pedestal's destroy function). Would that be good enough as at least an intermediate fix?

**Comment by leggettc18** [comment]
Here's what it looks like. Not quite as smooth as the N64 rando but I'd say not too shabby.
https://user-images.githubusercontent.com/21345721/176980223-7f1f557d-cdff-49e0-86d7-ef3e07f33bba.mp4

**Comment by briaguya-ai** [comment]
calling this good for now, if we feel like making it happen at the pedestal instead of in the doorway we can make a new issue for it
