### ISSUE TITLE
Opening Door of Time doesn't work when warping in

### ISSUE THREAD

**Issue by aMannus** [briaguya-ai/rando-issue-tracker#122]
The cutscene doesn't trigger correctly when the setting is set to "Closed" or "Intended" and warping into the Temple of Time. Leaving and entering makes it work again. Likely related to the flag that is set for watching a small cutscene for entering the Temple of Time for the first time.

**Comment by leggettc18** [comment]
OK, so DoT cutscene when prelude warping fix: I've added the entranceIndex for prelude warping as an or clause to all the effects that were happening at just the main entrance index before and it all works. Should I also lock the prelude entrance index check behind a rando flag check? Or would we be OK with vanilla saves checking for this as well?

**Comment by leggettc18** [comment]
To address my earlier comment, bria and aMannus agreed that missing the sound effects was less jarring than having an extra sound effect.
