### ISSUE TITLE
Item Tracker background color do not apply when pinned or docked

### ISSUE THREAD

**Issue by marclemieux64** [briaguya-ai/rando-issue-tracker#125]
So yeah we can make the item tracker transparent but when we pin into the bar or dock it the transparency do not stay.

**Comment by marclemieux64** [comment]
ok ^^ i'm on it

**Comment by aMannus** [comment]
It makes sense the transparent color doesn't stay. There's nothing behind the tracker if you dock it, so it'll be black. If you want it to overlay the actual game, you shouldn't be docking it.

**Comment by marclemieux64** [comment]
you are right now I understand why but what I'm looking for  would be to do something like this.
![Screenshot_27(edited)](https://user-images.githubusercontent.com/93109559/177962115-0b263962-2fb6-4b5d-9b93-0749eae5dc7c.png)
