### ISSUE TITLE
Ganon's Castle Trial setting not respected in all cases.

### ISSUE THREAD

**Issue by leggettc18** [briaguya-ai/rando-issue-tracker#131]
I had noticed in my latest seed that all of the light beams were present in Ganon's Castle with Number of Ganon's Trials set to 0. The Barrier was still missing so I didn't think too much of it. Then, Big Ol' Gang in discord found that despite having 2 Ganon's Trials set on their seed, the barrier was already down. There seems to be some kind of bad flag getting set somewhere, possibly due to a similar situation to the completed dungeons getting set from the save file above instead of getting set to 0.

**Comment by DouglasOwen** [comment]
[file2.sav.txt](https://github.com/briaguya-ai/rando-issue-tracker/files/9073807/file2.sav.txt)
[13223.json.txt](https://github.com/briaguya-ai/rando-issue-tracker/files/9073815/13223.json.txt)


Adding files per request.

**Comment by leggettc18** [comment]
So for v1 we're going to remove the option for the number of trials and replace it with a checkbox, so either none of them or all of them. Our current implementation only requires 2 trials, no matter which ones, whereas the 3ds item randomization logic picks specific trials to be completed. Changing our implementation of the Logic will come in v2.

On top of that, we need to find whatever bug caused @DouglasOwen to have no barrier despite having Ganon's Trials set to 2.
