### ISSUE TITLE
Crash leaving ganon's castle

### ISSUE THREAD

**Issue by Drihscol** [briaguya-ai/rando-issue-tracker#149]
Build: Jul 7 08:11:45 (current pinned)
Leaving ganon's castle crashes the game for me

https://streamable.com/f0m3nt

[file1.sav.log](https://github.com/briaguya-ai/rando-issue-tracker/files/9078435/file1.sav.log)
[356.json.log](https://github.com/briaguya-ai/rando-issue-tracker/files/9078436/356.json.log)

**Comment by aMannus** [comment]
Closing because this is fixed in latest dev and the fix is just a matter of time before it's merged into the rando builds. It's skybox bug when hyrule field is never loaded before going to Outside Ganon's Castle.
