### ISSUE TITLE
Lake Hylia not rising after beating Water Temple

### ISSUE THREAD

**Issue by Flax4** [briaguya-ai/rando-issue-tracker#24]
Tried it my self in Rando, could reproduce. I could not reproduce in Dev.

https://clips.twitch.tv/PricklyFitJellyfishPoooound-VuDW3_obN0RLaBAs

**Comment by briaguya-ai** [comment]
leaving a note to also implement the change water level gossip stone with this

**Comment by briaguya-ai** [comment]
since no checks rely on lowered water, the gossip stone water level changer can be post v1 https://github.com/briaguya-ai/rando-issue-tracker/issues/26
