### ISSUE TITLE
[N64 Rando Parity] Toggle certain skips

### ISSUE THREAD

**Issue by aMannus** [briaguya-ai/rando-issue-tracker#37]
Skip tower escape sequence, skip child stealth section, complete mask quest as soon as you have visited zelda, free scarecrow song (pulling out ocarina near pierre will instantly make him appear).

Not sure if it would be easier to have seperate issues for every single one or not.

**Comment by briaguya-ai** [comment]
@aMannus it'd be better to have these split all of these up into separate issues.
