### ISSUE TITLE
Missing cutscene skips

### ISSUE THREAD

**Issue by aMannus** [briaguya-ai/rando-issue-tracker#38]
There's a few cutscenes that aren't skipped yet. 

- Spirit Temple, cutscene before and after the gerudo iron knuckle fight.
- Spirit Temple, cutscene after defeating twinrova. 
- After defeating ganondorf, tower breaking down. (not sure how that is handled in N64 rando because I usually play with skip tower escape sequence on)
- Phantom Ganon defeat cutscene
- Jabu Jabu. Ruto 3 cutscenes. 1: Talking to her before dropping down in the hole, another when talking to her to pick her up. Third is after defeating Barinade and stepping into the blue warp

There's possibly more that I just can't think of right now. 

Also I think briaguya was talking about the twinrova cutscene that is skipped right now being too fast and twinrova giving you no time to climb up to the platform before attacking.

**Comment by briaguya-ai** [comment]
we should split this up into separate issues

spirit temple stuff is <https://github.com/briaguya-ai/rando-issue-tracker/issues/5>

tower breaking down can go in the same issue as skip tower escape (skipping the cutscene as desired behavior for having skip tower escape unchecked, skipping straight to the ganon fight as desired behavior for having skip tower escape checked
