### ISSUE TITLE
raveyard/disco dampe/graveyard acid trip/weird colors in graveyard

### ISSUE THREAD

**Issue by briaguya-ai** [briaguya-ai/rando-issue-tracker#4]
not sure what's causing this

![image](https://user-images.githubusercontent.com/70942617/176243113-bff9fefe-5079-45a0-8963-a438f10fed89.png)
![image](https://user-images.githubusercontent.com/70942617/176243124-5b4addad-792d-41d9-a984-02d3f479e0cb.png)
![image](https://user-images.githubusercontent.com/70942617/176243131-9cb103ac-5337-4224-b7a1-bfa575284990.png)

**Comment by briaguya-ai** [comment]
Big Ol' Gang on disc ran into this today

![image](https://user-images.githubusercontent.com/70942617/177051010-4337a739-61c0-49ec-bd8a-19e539be1c74.png)

still not sure what's causing it

**Comment by aMannus** [comment]
Additionally Big Ol' Gang said he couldn't reproduce in latest dev

**Comment by leggettc18** [comment]
I got video of it, if this helps find the cause somehow

https://user-images.githubusercontent.com/21345721/177900281-bb4b118a-5903-4108-b5f1-dd977b899974.mp4

.

**Comment by leggettc18** [comment]
It seems to happen after getting into proximity of the Royal Family's tomb. Everything seems normal until the lightning strike happens. Then the lighting looks mostly normal but seems to get stuck brighter. Then the trippiness starts.

My video has me leaving the tomb but it's not required to leave from there, just to get close to it. Walking into the graveyard initially does not have this happen, but it starts happening shortly after you get close to the tomb. Most likely has something to do with the weather effects.

**Comment by leggettc18** [comment]
It was related to the cosmetics editor and custom interface colors somehow. The pinned build I could consistently repro this on was before Baoulettes' rewrite of the cosmetics editor, and after that was merged in I could no longer reproduce raveyard.

**Comment by briaguya-ai** [comment]
closing this since it's fixed with the new cosmetics menu, the rave will live on in our hearts
