### ISSUE TITLE
[N64 Rando Parity] Toggle Skip Child Stealth Section

### ISSUE THREAD

**Issue by aMannus** [briaguya-ai/rando-issue-tracker#40]

**Comment by briaguya-ai** [comment]
64rando: skip child zelda+skip child stealth
* blocks moved
![image](https://user-images.githubusercontent.com/70942617/176847519-17bd0669-d2f5-48de-ab5e-7d5ef931622b.png)
* warp to zelda when going in anyways

64rando: skip child zelda+no skip child stealth
* blocks moved
* guards blocking when you go in

it seems allowing the player to choose either skip or not skip for child stealth even when skip child zelda is selected shouldn't cause any problems
