### ISSUE TITLE
Add particles to the model of warp songs to distinguish from normal songs

### ISSUE THREAD

**Issue by aMannus** [briaguya-ai/rando-issue-tracker#43]
This has been discussed before, adding this for completion sake. 

Same particles potentially useful for #6 and #18

**Comment by briaguya-ai** [comment]
marked as maybe v1 for now, this should be doable but if we can't figure out the underwater/boss room rendering issues in time for v1 we can look into other options or just putting it off

**Comment by PurpleHato** [comment]
Done with https://github.com/briaguya-ai/Shipwright/pull/209
