### ISSUE TITLE
Missing Jabu Jabu cutscene skips

### ISSUE THREAD

**Issue by aMannus** [briaguya-ai/rando-issue-tracker#46]
3 ruto cutscenes. 

1: Talking to her before dropping down in the hole. N64 rando has ruto already down the hole even when entering jabu for the first time.

2: When talking to her after she's already down the hole, before being able to pick her up. This is just a short text box.

3: After defeating Barinade and stepping into the blue warp where ruto talks to you before warping out to Zora's Fountain.

**Comment by briaguya-ai** [comment]
@aMannus could you link a timesamp of 64 rando footage for the blue warp part?

**Comment by aMannus** [comment]
https://youtu.be/9UfEYaPOv3Y?t=3866

Timestamp for first 2 ruto cutscenes in N64 rando
