### ISSUE TITLE
Missing skip for shadow temple lore prompts

### ISSUE THREAD

**Issue by aMannus** [briaguya-ai/rando-issue-tracker#47]
List of prompts I've been able to find, there might be more.

TextID: 023C, 030D (not sure which is the correct one)
The shadow will yield only to one with the eye of truth, handed down in Kakariko Village

TextID: 020A (occurs 2 times)
One who gains the eye of truth will be able to see what is hidden in the darkness.

TextID: 0208 (occurs 4 times)
Shadow Temple...
Here is gathered Hyrule's bloody history of greed and hatred...

TextID: 0209 (occurs 2 times)
What is hidden in the darkness...
Tricks full of ill will...
You can't see the way forward...

TextID: 0224
Make my beak face the skull of truth. 

The alternative is descent into the deep darkness.

**Comment by leggettc18** [comment]
I'd like to take a look at this if no one else has claimed it. I don't seem to have the ability to self-assign it like Dog did for the Ganon hint text.

**Comment by leggettc18** [comment]
Looks like they set the following Temp Clear flags in the shadow temple scene. I thought I remembered only ever seeing them once per playthrough in the past but they clear when exiting and leaving. In fact the bottom two cleared while I was still in the temple and those textboxes reocurred. So setting those flags during save generation is out. But knowing which flags should make it easier to find where they occur in the code to prevent them from triggering.

![image](https://user-images.githubusercontent.com/21345721/176798361-6cc41b60-1da3-49e2-9121-1c2a552ee719.png)

**Comment by leggettc18** [comment]
Fix is in a PR now. https://github.com/briaguya-ai/Shipwright/pull/250
