### ISSUE TITLE
spirit temple post boss key door

### ISSUE THREAD

**Issue by briaguya-ai** [briaguya-ai/rando-issue-tracker#5]
spirit post boss door should match 64rando (cutscene skips/boss triggers etc.) need to do some research/testing

<https://youtu.be/i9IK9vVMsRU?t=3532>

so looking through the video the intro cutscene is definitely skipped, that cutscene seems to be what loads in the iron knuckle, i tried extracting stuff from the .otr to see what that cutscene is doing but i'm pretty lost as to what the `gSpiritBossNabooruKnuckleIntroCs` file actually *is*...
```c
#define gSpiritBossNabooruKnuckleIntroCs "__OTR__scenes/jyasinboss_scene/gSpiritBossNabooruKnuckleIntroCs"
#define gSpiritBossNabooruKnuckleDefeatCs "__OTR__scenes/jyasinboss_scene/gSpiritBossNabooruKnuckleDefeatCs"
```

it seems the defeat cutscene is also skipped in 64rando

another thing i noticed is soh rando currently kotake and koume are already flying around as soon as link enters twinrova's lair, in 64 rando they seem to start rising up when link gets on top of the platform (<https://youtu.be/i9IK9vVMsRU?t=3584>)

**Comment by aMannus** [comment]
For reference, here's a timestamp to N64 rando spirit temple past the boss key door.

https://youtu.be/hwlP6zlA6Dk?t=7930

**Comment by aMannus** [comment]
I'll take a stab at it

**Comment by briaguya-ai** [comment]
the idea of replacing the iron knuckle with a standard one was floated, but there are enough differences between the 2 combat wise (hp/armor loss) that makes that seem less than ideal

**Comment by aMannus** [comment]
PR made for the first 2 cutscenes, made a new issue for the twinrova cutscene so we can tackle that seperately.

**Comment by briaguya-ai** [comment]
closing this, it continues in #95
