### ISSUE TITLE
Saved Gorons appear in Goron City as adult before Fire Temple.

### ISSUE THREAD

**Issue by Vsmit** [briaguya-ai/rando-issue-tracker#50]
Title says it all, really. Haven't set foot in Fire Temple but all of the caged Gorons appear in Goron City as though the temple is complete.

Went into FT after to see if it would flag them as unsaved. Gorons still in cages in FT, no change in GC.

~~v154~~ v156

**Comment by briaguya-ai** [comment]
looks like the goron city gorons check for the fire medallion, not having beaten the fire temple

working on a fix rn
