### ISSUE TITLE
Shorten/remove opening the Royal tomb cutscene

### ISSUE THREAD

**Issue by Flax4** [briaguya-ai/rando-issue-tracker#52]
Comparison:

N64
https://user-images.githubusercontent.com/50862920/176651890-b36625f1-dfb5-4324-89e8-e19224237671.mp4

Soh
https://user-images.githubusercontent.com/50862920/176653271-aeeb68b9-5001-4593-babb-aacb8b139239.mp4

**Comment by leggettc18** [comment]
Been digging into this a bit. Here's what I've got so far. Need to find a way to get the explosion sound effect to play correctly (or just cut it out) but functionally this seems pretty good

https://user-images.githubusercontent.com/21345721/176984836-9948ad6b-870b-42d9-a522-4bdf8adc6b97.mp4

.

**Comment by leggettc18** [comment]
Actually figured out the visual snags even faster than I thought I would

https://user-images.githubusercontent.com/21345721/176985738-17bf34b9-8669-4edd-aaa6-be6baf64c3fa.mp4

.
