### ISSUE TITLE
Shorten flying with Owl cutscenes

### ISSUE THREAD

**Issue by Flax4** [briaguya-ai/rando-issue-tracker#53]
Shorten the flying cutscenes with Lake Hylia and Death Mountain Trail Owls.
Sidenote: The Lake Hylia Owl's first text line doesn't work mashing through, on N64 rando it does.

N64:
Hylia : https://user-images.githubusercontent.com/50862920/176655603-5e023ba1-f03b-49a6-9ca2-cb99c476689d.mp4

Trail : https://user-images.githubusercontent.com/50862920/176655638-8658150a-33dc-4340-bb63-31dede73ca11.mp4

SoH:
Hylia : https://user-images.githubusercontent.com/50862920/176655770-cd1ae4a8-e853-4c4f-a914-b245c2e9e974.mp4

Trail : https://user-images.githubusercontent.com/50862920/176655820-06e1b290-3ae7-44e0-b09c-f9ef95f1cf6c.mp4

**Comment by leggettc18** [comment]
Something to note here for whoever ends up implementing this. I believe for the Lake Hylia cutscene, 3ds rando has an option to keep it in, as players can see the item on top of the lab during the cutscene.

**Comment by briaguya-ai** [comment]
> Something to note here for whoever ends up implementing this. I believe for the Lake Hylia cutscene, 3ds rando has an option to keep it in, as players can see the item on top of the lab during the cutscene.

seems that's the case, it's `LakeHyliaOwl` in `settings.cpp` in 3drando

i'll make skipping that a timesaver option

**Comment by leggettc18** [comment]
As we discovered shortly after bria's comment in the Discord, in SoH you actually can't see the top of the lab during the cutscene. Most likely the FoV is different in the 3DS version. So probably no need to worry about this unless we get FoV slider options down the road that open up this possibility.
