### ISSUE TITLE
goron link not rolling

### ISSUE THREAD

**Issue by briaguya-ai** [briaguya-ai/rando-issue-tracker#60]
**expected behavior**
| beat fire temple | bombed/stopped him before | is rolling |
| - | - | - |
| yes | yes | no |
| no | yes | no |
| yes | no | yes |
| no | no | yes |

note: "bombed/stopped him before" involves talking to him

**Comment by briaguya-ai** [comment]
in my testing this is working as expected, but @Vsmit report of goron link not rolling when he should

**Comment by Vsmit** [comment]
[18750.json.txt](https://github.com/briaguya-ai/rando-issue-tracker/files/9031779/18750.json.txt)

Normally, when you stop the rolling Goron in GC as a child it will activate flag inf_table[17] 0x0e. If the reward for that check is the Goron Tunic, it will _also_ activate inf_table[16] 0x09, which will open the Goron Shop and Darunia's room as an adult and prevent Link the Goron from rolling without being bombed.
