### ISSUE TITLE
conditionally play CORRECT_CHIME when loading spoilers

### ISSUE THREAD

**Issue by briaguya-ai** [briaguya-ai/rando-issue-tracker#75]
now that we're loading/aprsing in spoilers on file select screen init, the call to
```cpp
Audio_PlaySoundGeneral(NA_SE_SY_CORRECT_CHIME, &D_801333D4, 4, &D_801333E0, &D_801333E0, &D_801333E8);
``` 
in `ParseItemLocationsFile` in `randomizer.cpp` happens as soon as the file select screen loads with randomizer enabled

it also plays at the same time as `HORSE_GOAL` when generating a spoilerfile from the settings menu

we should probably have some logic around when we want this to play, or just disable the sound entirely

**Comment by PurpleHato** [comment]
I think we should conserve the sound once the generation is done
But add an additionnal bool once the game is on it's initial booting phase / soft reset phase that will affect if it's played or not
