### ISSUE TITLE
Mashing "B" (or holding "R") after playing Lullaby for Great Fairy can cancel out getting the Item

### ISSUE THREAD

**Issue by Flax4** [briaguya-ai/rando-issue-tracker#94]
As soon as you play Lullaby for a Great Fairy and mash the "B" button while having a sword equipped, there is a chance you'll slash your sword right before getting the item and cancel it out and prevent you from getting the item. Leaving and entering again will not grant you the item either, nor will a save and reset.
 
https://clips.twitch.tv/ArtisticLightDootM4xHeh-3nfPRIW_Cyz5LFeT

**Comment by briaguya-ai** [comment]
i was able to reproduce this, it's difficult to reproduce with breakpoints though due to the whole needing to mash thing

it seems the flag is getting set even if the item isn't being given, but i'm not sure what it is about slashing the sword that's preventing the item from being given

i'm also not sure what the best way to go about fixing this would be...

**Comment by leggettc18** [comment]
This might be a similar situation to what I was encountering when fixing Prelude Check. The code to give the player an item just sets player->getItemId, and it seems to get evaluated on the next frame. But if something overwrites that getItemId before it gets processed,then you don't get the item. Or at least something like that was happening with Prelude while near the sword pedestal. Maybe swinging the sword does something with the getItemId?

**Comment by briaguya-ai** [comment]
looks like crouching does it too https://clips.twitch.tv/SmoggyConfidentTeaPermaSmug-6PgoveFvg6wy5vRj

**Comment by briaguya-ai** [comment]
just a note that we should be looking around here https://github.com/briaguya-ai/Shipwright/blob/54835bf8653fd1a09b5aa45f843eef451d26760b/soh/src/overlays/actors/ovl_Bg_Dy_Yoseizo/z_bg_dy_yoseizo.c#L70-L82
