### ISSUE TITLE
make sure **ALL** the strings for generating the spoilerfile and reading the spoilerfile match in french

### ISSUE THREAD

**Issue by briaguya-ai** [briaguya-ai/rando-issue-tracker#99]
melon ran into a crash and the problem ended up being a capitalization mismatch

fixed that one with https://github.com/briaguya-ai/Shipwright/pull/286, but we need to make sure there are no places where they don't match

**Comment by PurpleHato** [comment]
Should be completly done with: https://github.com/briaguya-ai/Shipwright/pull/288
